name: Tests
on: [push]
jobs:
  tests:
    name: ${{ matrix.peewee-backend }} - ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: peewee
          MYSQL_DATABASE: peewee_test
        ports:
          - 3306:3306
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: peewee
          POSTGRES_DB: peewee_test
        ports:
          - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.11", "3.13"]
        peewee-backend:
          - "sqlite"
          - "postgresql"
          - "mysql"
        exclude:
          - python-version: 2.7
            peewee-backend: postgresql
          - python-version: "3.13"
            peewee-backend: postgresql
        include:
          - python-version: "3.11"
            peewee-backend: cockroachdb
          - python-version: "3.11"
            peewee-backend: psycopg3
          - python-version: "3.13"
            peewee-backend: psycopg3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: deps
        env:
          PGUSER: postgres
          PGHOST: 127.0.0.1
          PGPASSWORD: peewee
        run: |
          pip install setuptools psycopg2-binary cython pymysql 'apsw' mysql-connector sqlcipher3-binary 'psycopg[binary]' pysqlite3
          python setup.py build_ext -i
          psql peewee_test -c 'CREATE EXTENSION hstore;'
      - name: crdb
        if: ${{ matrix.peewee-backend == 'cockroachdb' }}
        run: |
          wget -qO- https://binaries.cockroachdb.com/cockroach-v22.2.6.linux-amd64.tgz | tar xz
          ./cockroach-v22.2.6.linux-amd64/cockroach start-single-node --insecure --background
          ./cockroach-v22.2.6.linux-amd64/cockroach sql --insecure -e 'create database peewee_test;'
      - name: runtests ${{ matrix.peewee-backend }} - ${{ matrix.python-version }}
        env:
          PEEWEE_TEST_BACKEND: ${{ matrix.peewee-backend }}
          PGUSER: postgres
          PGHOST: 127.0.0.1
          PGPASSWORD: peewee
        run: python runtests.py --mysql-user=root --mysql-password=peewee -s -v2
